name: dev


on:
 push:
   branches:
     - dev
jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
       node-version: 16
    - name: Install dependencies
      run: npm install --no-audit --no-fund --no-optional
    - name: lint 
      run: npm run eslint
    - name: test
      run: npm run test
    - name: build
      run: npm run build


