name: Development


on:
 push:
   branches:
     - dev
jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
       node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Unit Testing
      run: npm run test

