name: development

on:
 push:
   branches: [dev]
 pull_request:
   branches: [dev]
   types: [opened, synchronize]

jobs:
  development:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
       node-version: 16
    - name: install
      run: npm install --no-audit --no-fund
    - name: lint 
      run: npm run lint
    - name: test
      run: npm run test
    - name: build
      run: npm run build
